version: '3.9'

services:
  collaboration-service-js:
    image: collab-service-js-local
    ports:
      - 4444:4444
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.2.2
    ports:
      - '6379:6379'

networks:
  default:
    name: explorviz
